# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 3.0.1
maven_group = me.johnadept
archives_name = auto_attack
enabled_platforms = fabric

# Mod Info
mod_id=auto_attack
mod_name=Ice 
mod_description=A mod that automatically strikes when the attack indicator is full.
mod_authors= ImmortqlBirth
mod_license=MIT

# Minecraft properties
minecraft_version=1.21.11

# Dependencies
architectury_api_version = 17.0.6
fabric_loader_version = 0.17.0
fabric_api_version = 0.129.0+1.21.7
neoforge_version = 21.7.8-beta
cloth_config_version = 19.0.147

# Fabric Only Dependencies
modmenu_version = 15.0.0-beta.3

# Neoforge Only Dependencies
